service: fresh-serverless-cljs

provider:
  name: aws
  runtime: nodejs4.3

functions:
  echo:
    cljs: fresh-serverless-cljs.core/echo
    events:
      - http:
          path: echo
          method: post

plugins:
  - serverless-cljs-plugin
