service: joke-generator-firebase

provider:
  name: aws
  runtime: nodejs4.3

functions:
  echo:
    cljs: joke-generator-firebase.core/echo
    events:
      - http:
          path: echo
          method: post

plugins:
  - serverless-cljs-plugin
